### PR TITLE
Registration and Login

### PR DESCRIPTION
**Pull request by nosvalds**
# Summary
This pull request adds 2 routes to the API to enable registration of a user from the frontend and then login. The login request returns a bearer token that should be included in requests from a user to allow them access to their records in the database. If the frontend makes a request without a bearer token for any of the routes not related to the registration workflow, then they will receive and "unauthenticated" response. 

# Detailed Documentation
(this has been added in the Readme.md as well)

#### Request
```json
{
    "name": "Test User 1", // REQ, full name
    "email": "test@test2.com", // REQ, valid email, not the same as another in the database
    "password": "iliketurtles" // REQ, password
}
```

##### Success
```json
{
    "success": {
        "token": "<token>"
    }
}
```

##### Failures
- Missing name
- Missing email
- Missing password
- Duplicate User (email must be unqiue)

```json
{
    "message": "The given data was invalid.",
    "errors": {
        "name": [
            "A name is required to create a user account"
        ],
        "email": [
            "A email is required to create a user account"
        ],
        "password": [
            "A password is required to create a user account"
        ],
        "email": [
            "A user account exists already with this email"
        ],
    }
}
```

#### Request
```json
{
    "username": "test@test2.com", // REQ, valid user email
    "password": "iliketurtles" // REQ, password
}
```

##### Success
```json
{
    "token_type": "Bearer",
    "expires_in": 31536000,
    "access_token": "<token>",
    "refresh_token": "<token>"
}
```

##### Failures
- Missing username/password

```json
{
    "error": "invalid_request",
    "error_description": "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.",
    "hint": "Check the `< missing >` parameter",
    "message": "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed."
}
```
- Invalid username/password

```json
{
    "error": "invalid_grant",
    "error_description": "The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.",
    "hint": "",
    "message": "The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."
}
```

### Not Logged In/Unauthenticated
- If the frontend tries to make a request to any of the non-authentication workflow related routes without the proper Bearer Token, they will receive this response:
```json
{
    "message": "Unauthenticated."
}
```

### CODE REVIEW

**Review by kierancott — APPROVED** [review]
Looks great! Let's discuss later this morning.

**Comment by nosvalds** [comment]
Discussed on standup this morning. Need to add a few features to the basic Auth workflow before merging:

## To Do
- Send back Name on Login - to be stored as user details in state for the Account Dashboard page
- Account Dashboard - PATCH allow for editing name, email
  - We will not allow changing password here for the MVP, users can change password using forgot password if necessary
- Forgot Password route
  - Nik to investigate how to implement this. A requirement for the MVP.

**Comment by nosvalds** [comment]
## Changes Completed
- Complete - Forgot Password routes 
  - /reset-password-without-token - complete
  - email formatting  - complete
  - Mailjet integration - complete
  - /reset-password-with-token - complete
- Complete - Send back Name on Login - to be stored as user details
- Complete - Account Dashboard - PATCH allow for editing name, email
- Complete -  Account Dashboard - DELETE - delete account 

### Full Details (in documentation as well) 

### Register User - POST `/api/register`

#### Request
```json
{
    "name": "<user name>", // REQ, full name
    "email": "<email>", // REQ, valid email, not the same as another in the database
    "password": "<password>" // REQ, password
}
```

#### Responses

##### Success
```json
{  
    "success": {
        "token": "<token>"
    },
    "user": {
        "id": "<ID>",
        "name": "<user name>",
        "email": "<email>",
        "created_at": "2020-09-01 14:22:46"
    }
}
```

##### Failures
- Missing name
- Missing email
- Missing password
- Duplicate User (email must be unqiue)

```json
{
    "message": "The given data was invalid.",
    "errors": {
        "name": [
            "A name is required to create a user account"
        ],
        "email": [
            "A email is required to create a user account"
        ],
        "password": [
            "A password is required to create a user account"
        ],
        "email": [
            "A user account exists already with this email"
        ],
    }
}
```

### Login User - POST `/api/login`

#### Request
- ***NOTE: `username` maps to `email` in this case***
```json
{
    "username": "<user email>", // REQ, valid user email
    "password": "<password>" // REQ, password
}
```

#### Responses

##### Success
```json
{
    "token_type": "Bearer",
    "expires_in": 31536000,
    "access_token": "<token>",
    "refresh_token": "<token>",
    "user": {
        "id": 20,
        "name": "<user name>",
        "email": "<email>",
        "created_at": "2020-09-01 14:22:46"
    }
}
```

##### Failures
- Missing username/password

```json
{
    "error": "invalid_request",
    "error_description": "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.",
    "hint": "Check the `< missing >` parameter",
    "message": "<same as error_description>"
}
```
- Invalid username/password

```json
{
    "error": "invalid_grant",
    "error_description": "The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.",
    "hint": "",
    "message": "<same as error_description>"
}
```

### Not Logged In/Unauthenticated
- If the frontend tries to make a request to any of the non-authentication workflow related routes without the proper Bearer Token, they will receive this response:
```json
{
    "message": "Unauthenticated."
}
```

### Forgot Password / Password Reset Routes

### `POST /api/reset-password-without-token`

#### Request
```json
{
    "email": "<email>", // REQ, valid user email
}
```

#### Responses

##### Success
```json
{
    "message": "Reset Password email successfully sent"
}
```

##### Failure
- No email supplied/invalid email format

```json
{
    "message": "The given data was invalid.",
    "errors": {
        "email": [
            "An email is required to reset the password" // "A valid email must be used to reset the password"
        ]
    }
}
```

- User does not exist with that email

```json
{
    "message": "An account does not exist with this email address"
}
```

- Email failed
```json
{
    "message": "An error has occured sending the reset password email, please try again",
    "error": "<error message>"
}


```
### `POST /api/reset-password-with-token`

#### Request
```json
{
    "email": "<email>", // REQ, valid user email
    "password": "<new password>", // REQ, new password
    "token": "<reset token>", // REQ, valid reset token from email
}
```

#### Responses

##### Success
```json
{
    "message": "Password Reset Successful",
    "user": {
        "id": 21,
        "name": "<name>",
        "email": "<email>",
        "created_at": "2020-09-03 11:16:06"
    },
    "token": "<bearer token>"
}
```

##### Failure
- Similar email, password, token validation as before (required)
- Invalid token, or they've already reset their password
```json
{
    "message": "Password token invalid, please submit a new password reset request"
}
```

### Update User Account - PATCH `/api/user/{user id}`

#### Request
```json
{
    "email": "<email>", // OPT, valid user email, not duplicate
    "name": "<user name>" // OPT, string
}
```

#### Responses

##### Success
- Returns the user object
```json
{
    "user": {
        "id": 23,
        "name": "NickelNood",
        "email": "nosvalds@gmail.com",
        "created_at": "2020-09-04 14:15:57"
    }
}
```

##### Failures
- Trying to update a different user than you are logged in as
```json
{
    "message": "You cannot edit a user other than your own"
}
```

- Trying to update to a Duplicate email in the database

```json
{
    "message": "The given data was invalid.",
    "errors": {
        "email": [
            "A user account exists already with this email"
        ]
    }
}
```

- Incorrect format(s) name or email
```json
{
    "message": "The given data was invalid.",
    "errors": {
        "email": [
            "The email must be a valid email address."
        ]
    }
}
```

### DELETE User Account - DELETE `/api/user/{user id}`

#### Responses

##### Success
- Returns a 204 - No Content response

##### Failures
- Trying to delete a user other than your own
```json
{
    "message": "You cannot delete a user other than your own"
}
```
- Trying to delete a user that does not exist
```json
{
    "message": "No query results for model [App\\User] <ID>"
}
```

**Review by aejgardner — APPROVED** [review]
Looks great Nik, nice one!

**Pull request merged**
